### ISSUE TITLE
Consider using GitHub releases so that pinning versions is easier

### ISSUE THREAD

**Issue by JohnRoesler** [jasonlvhit/gocron#123]
Right now, in order to pin to a specific version of gocron - I have to know the commit and commit date/time I want to point on master.

If we use github releases - then pulling with go mod allows to set the version pin. For example:

```diff
- 	github.com/jasonlvhit/gocron v0.0.0-20191103124442-96e810119cd2
+ 	github.com/jasonlvhit/gocron v1.0.1

**Comment by JohnRoesler** [comment]
@preslavrachev @Streppel

**Comment by Streppel** [comment]
Completely agree. I'll be creating a version 0.5 as a pre-release as we still need to merge a really important PR that adds production safety (but currently has some code conflicts) and work on some code and tests to fix problems like #19 and #50 in order to consider this package to be production ready. What do you think?

**Comment by JohnRoesler** [comment]
Yes i think that makes sense. A big thing I'd like to see is a way to have errors passed back out (channel maybe) so that I could decide how to handle different errors that may occur during my cron's run.

**Comment by Streppel** [comment]
And from now on we have our pre-release version 0.1! 

https://github.com/jasonlvhit/gocron/releases/tag/0.1
