### ISSUE TITLE
[question] Scheduling for Month

### ISSUE THREAD

**Issue by aimazh** [jasonlvhit/gocron#27]
Do we have an opportunity to see in the future something like `Every(1).Month().At("00:00")`? Or is there another way to achieve it?
`---`
best regards!
aibk

**Comment by dabba39** [comment]
or a birthday greeter, like Every(1).Year().At("November 7 08:00") ?

**Comment by paveldanilin** [comment]
@kaiiak Hi!
I am sorry for raising that question again, but how to create a monthly scheduled job?
I tried to use the approach from the README and schedule the job at a specific date/time

`// Begin job at a specific date/time
	t := time.Date(2020, time.November, 10, 15, 0, 0, 0, time.Local)
	gocron.Every(1).Hour().From(&t).Do(task)`

But the job is being executed every hour, instead of singular run at a specific date/time.
